### ISSUE TITLE
make evm-simulation fails

### ISSUE THREAD

**Issue by RafaelAPB** [metacraft-labs/DendrETH#45]
Following the steps as described in the documentation work until ``yarn install``. 
The step with ``make evm-simulation`` fails with output:

https://gist.github.com/RafaelAPB/c789f91817486f2591fa807188f27924

**Comment by PetarKirov** [comment]
Hi @RafaelAPB and thanks for checking out the project! In all likelihood, the problem is caused by the environment variable `USER_PRIVATE_KEY` which is not set on your computer. You simply need to set it to a valid Ethereum private key (hex-encoded secp256k1 key), e.g. `0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80` (just an example - the first private key for the accounts that Hardhat generates).

However, if you were Nix (as described in the readme), this situation should not be possible :smile: - the `.envrc` will refuse evaluate, because it [checks](https://github.com/metacraft-labs/DendrETH/blob/e32eea5f1487b179e679245741f82b5066cf378b/.envrc#L17-L26) whether this (and other) variables are set.

Nonetheless, we have opened [a PR](https://github.com/metacraft-labs/DendrETH/pull/46), which should provide a fallback for this case.

**Comment by RafaelAPB** [comment]
Thanks for the quick answer, @PetarKirov. As far as I know, the Nix environment setup was successful. Maybe I missed something.

**Comment by PetarKirov** [comment]
> I think the source of confusion is indicating to run `nix develop` instead of `direnv allow` - I suppose that in this case the checks aren't done.

You're right - I will review the docs and update them to make this more clear - although `direnv allow` is not technically required, it's highly recommended.

> Running direnv allow doesn't seem to enforce the definition of the variables, at least in a MacOS. Setting a .env at the project root doesnt' seem the test work either.

Sounds like you have `direnv` installed, but you haven't integrated it with your shell - please check this page in their docs: https://direnv.net/docs/hook.html

**Comment by RafaelAPB** [comment]
yep @PetarKirov, spot on!
